#### general settings
name: refusion
use_tb_logger: true
model: denoising
distortion: deshadow
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 50
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1
  
#### datasets
datasets:
  train:
    optimizer: Lion # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /content/Shabby_pages_1000/train/clean
    dataroot_LQ: /content/Shabby_pages_1000/train/shabby

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 4
    GT_size: 256
    LR_size: 256
    use_flip: False
    use_rot: False
    color: gray
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /content/Shabby_pages_1000/validate/clean
    dataroot_LQ: /content/Shabby_pages_1000/validate/shabby
    color: gray

#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 32
    enc_blk_nums: [1, 1, 2, 4]
    middle_blk_num: 6
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 2e-4
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.999
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq:  !!float 5e3
